/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.view;

import com.mongodb.BasicDBObject;
import com.mongodb.Block;
import com.mongodb.DBObject;
import com.mongodb.client.MongoClient;
import com.mongodb.client.MongoClients;
import java.util.ArrayList;
import java.util.Calendar;
import org.bson.Document;
import com.model.Documento;
import com.model.Funcionario;
import com.utils.UppercaseDocumentFilter;
import com.sun.glass.events.KeyEvent;
import com.utils.BancoDeDados;
import java.awt.Image;
import java.util.Date;
import java.util.function.Consumer;
import javax.swing.ImageIcon;
import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;
import org.bson.BSON;

/**
 *
 * @author x002559
 */
public class JPFuncionario extends javax.swing.JPanel {

    /**
     * Creates new form JPCadastro
     */
    private BancoDeDados database = new BancoDeDados();
    private ArrayList<String> converte = new ArrayList();
    private Calendar dataInicial = Calendar.getInstance();
    private DocumentFilter filter = new UppercaseDocumentFilter();
    private Document data;
    DBObject dbObj;
    private Consumer<Document> printBlock = new Consumer<Document>() {
        @Override
        public void accept(Document t) {
            System.out.println(data.toJson());
        }
    };
    /*private Block<Document> printBlock = new Block<Document>() {
        @Override
        public void apply(final Document t) {
            System.out.println(data.toJson());
        }
    };*/
    private String nome;
    private String nascimento;
    private String usuario;
    private String senha;
    private String periodo;

    public JPFuncionario() {
        initComponents();
        //Visitante visitante = new Visitante();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        lblNome = new javax.swing.JLabel();
        cmpNome = new javax.swing.JTextField();
        ((AbstractDocument) cmpNome.getDocument()).setDocumentFilter(filter);
        lblDocumento = new javax.swing.JLabel();
        cmpDocumento = new javax.swing.JTextField();
        lblTipo = new javax.swing.JLabel();
        cmpListaDoc = new javax.swing.JComboBox<>();
        lnlUsuario = new javax.swing.JLabel();
        cmpUsuario = new javax.swing.JTextField();
        lblSenha = new javax.swing.JLabel();
        lblLocal = new javax.swing.JLabel();
        cmpPeriodo = new javax.swing.JComboBox<>();
        lblDtNasc = new javax.swing.JLabel();
        cmpDtNasc = new javax.swing.JFormattedTextField();
        btCadastrar = new javax.swing.JButton();
        cmpSenha = new javax.swing.JPasswordField();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        lblNome.setText("Nome:");

        lblDocumento.setText("Documento:");

        cmpDocumento.setToolTipText("");
        cmpDocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmpDocumentoKeyPressed(evt);
            }
        });

        lblTipo.setText("Tipo:");

        cmpListaDoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RG", "RE", "CPF", "CPTS" }));

        lnlUsuario.setText("Usuario:");

        lblSenha.setText("Senha:");

        lblLocal.setText("Periodo:");

        cmpPeriodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Diurno", "Noturno" }));

        lblDtNasc.setText("Data de Nascimento:");

        try {
            cmpDtNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("    ## / ## / ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btCadastrar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btCadastrar.setText("Cadastrar");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cmpNome)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(cmpDtNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(117, 117, 117)
                                    .addComponent(cmpPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(20, 20, 20))
                                .addComponent(lblNome)
                                .addComponent(lblSenha)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblDocumento)
                                        .addComponent(cmpDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lnlUsuario))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblTipo)
                                        .addComponent(cmpListaDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblDtNasc)
                                    .addGap(131, 131, 131)
                                    .addComponent(lblLocal)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cmpUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                .addComponent(cmpSenha, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblNome)
                .addGap(6, 6, 6)
                .addComponent(cmpNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDtNasc)
                    .addComponent(lblLocal))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmpDtNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmpPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDocumento)
                        .addGap(6, 6, 6)
                        .addComponent(cmpDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTipo)
                        .addGap(6, 6, 6)
                        .addComponent(cmpListaDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lnlUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmpUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmpSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btCadastrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        // TODO add your handling code here:
        BancoDeDados bd = new BancoDeDados();
        Documento documento = new Documento();

        bd.iniciar();

        nome = cmpNome.getText();
        nascimento = cmpDtNasc.getText();
        documento.setNumeroDoc(cmpDocumento.getText());
        documento.setTipoDoc((String) cmpListaDoc.getSelectedItem());
        usuario = cmpUsuario.getText();
        senha = String.valueOf(cmpSenha.getPassword());
        periodo = (String) cmpPeriodo.getSelectedItem();
        //Funcionario funcionario = new Funcionario(nome, nascimento, documento, usuario, senha, periodo );
        //Document doc = bd.inserirFuncionario(funcionario);
        //bd.AddFuncionario(doc);
        cmpNome.setText("");
        cmpDtNasc.setText("");
        cmpDocumento.setText("");
        cmpListaDoc.getItemAt(0);
        cmpUsuario.setText("");
        cmpSenha.setText("");
        cmpPeriodo.getItemAt(0);
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void cmpDocumentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmpDocumentoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_ENTER) {
            database.iniciar();

            String doc = cmpDocumento.getText();

            //data = database.buscaDocFunc(doc);
            String jsonString = data.toJson();
            data = Document.parse(jsonString);
            cmpNome.setText((String) data.get("Nome"));
            cmpDtNasc.setText((String) data.get("Data de Nascimento"));
            cmpListaDoc.setSelectedItem((String) data.get("Tipo"));
            cmpUsuario.setText((String) data.get("Usuário"));
            cmpSenha.setText((String) data.get("Senha"));
            cmpPeriodo.setSelectedItem((String) data.get("Periodo"));
        }
    }//GEN-LAST:event_cmpDocumentoKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastrar;
    private javax.swing.JTextField cmpDocumento;
    private javax.swing.JFormattedTextField cmpDtNasc;
    private javax.swing.JComboBox<String> cmpListaDoc;
    private javax.swing.JTextField cmpNome;
    private javax.swing.JComboBox<String> cmpPeriodo;
    private javax.swing.JPasswordField cmpSenha;
    private javax.swing.JTextField cmpUsuario;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JLabel lblDocumento;
    private javax.swing.JLabel lblDtNasc;
    private javax.swing.JLabel lblLocal;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lnlUsuario;
    // End of variables declaration//GEN-END:variables
}
